[package]
name = "manifest-std"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = "0.14.1"
prost-types = "0.14.1"

[build-dependencies]
heck = "0.5.0"
prost = "0.14.1"
prost-build = "0.14.1"
prost-types = "0.14.1"

[features]
default = []